### ISSUE TITLE
Cocoapod support

### ISSUE THREAD

**Issue by skywalkerdude** [biobeats/swiftui-navigation-stack#18]
Could you also add this to cocoapods, for those who haven't yet migrated to SPM? :)

**Comment by jasonmercer** [comment]
I second this request :-)

**Comment by rtjinasjoe** [comment]
I third this request :)

**Comment by huybuidac** [comment]
4th =))

**Comment by matteopuc** [comment]
#27 `NavigationStack` now supports CocoaPods 🥳🥳 (README already updated). We must thank @pacu and @morellid 🙏 thank you so much guys!
