### ISSUE TITLE
ViewStack not persistent

### ISSUE THREAD

**Issue by CureleaAndrei** [biobeats/swiftui-navigation-stack#26]
Hi, thanks for this nice implementation. I've bumped into a problem. I have the rootView which is made out of some bottom view and  navigationViewStack. The bottom view needs to be displayed over some of the navigation stack, but not all of them. This rootView has a viewModel that controls the visibility of the bottom view and can be shared down the stack. After I navigate through the stack, when modifing the rootView viewModel the whole stack is reseting and the rootview is displayed. I think this is because of ViewStack is reinitialized. Making it persistent per navigation stack instance should resolve these kind of issues.  

P.S. : I've resolved this issue by making a singleton of HashMaps [id: NavigationStack] and a methode to get/add a new NavigationStack singletone inside NavigationStack class. The hashmap for maintaining the functionality of multiple navigations flow. Every navigation flow will have an id and from here it's own NavigationStack singletone. Inside the NavigationStackVIew init also ask for an id with the default "root" if it's not specified.

Also if you have a more elegant/efficient way of achieving this, please let me know.

**Comment by devendranrajesh** [comment]
I'm facing this issue too. Your approach looks simple to me.
Can you share the code on how you resolved this!
