### ISSUE TITLE
NavigationBar not presented

### ISSUE THREAD

**Issue by ImpacGroup** [biobeats/swiftui-navigation-stack#29]
Hi,

I really miss the possibility to add custom transitions in swiftui. So thank you for working on this framework.
Unfortunatly  if I switch from NavigationView to NavigationStackView the navigationbar disappears.

**Comment by matteopuc** [comment]
Hi @ImpacGroup, sorry for the late response. Unfortunately the `NavigationStack` doesn't support the navigation bar. Please, refer to #2
