### ISSUE TITLE
TextField or UITextView Representable not working

### ISSUE THREAD

**Issue by bluelobe** [biobeats/swiftui-navigation-stack#3]
If you have any TextField or a UITextView Representable object in any view that is inside NavigationStack, user is prevented from typing anything. The text just disappears.

e.g. 
TextField("test", text: $workingText)

**Comment by matteopuc** [comment]
Hi @bluelobe I guess I got your problem, but I'll show you an example, so that you can tell me if it's actually the problem you are experiencing. The problem is due to SwiftUI resetting all the `@State` properties when a view is removed from the hierarchy. It's not a SwiftUI bug, it's just a SwiftUI behaviour. Take a look at this example (you can copy paste it and try yourself):

```
import SwiftUI
import NavigationStack

struct ContentView : View {
    var body: some View {
        NavigationStackView {
            View1()
        }
    }
}

struct View1: View {
    @State private var text = ""

    var body: some View {
        ZStack {
            Color.yellow.edgesIgnoringSafeArea(.all)
            VStack {
                PushView(destination: View2()) {
                    Text("PUSH")
                }
                TextField("Type something...", text: $text)
            }
        }
    }
}

struct View2: View {
    var body: some View {
        ZStack {
            Color.green.edgesIgnoringSafeArea(.all)
            
            PopView {
                Text("POP")
            }
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```

The result is:

![Feb-08-2020 15-10-43](https://user-images.githubusercontent.com/5569047/74086658-3a73e100-4a85-11ea-9bd3-c9f8f23395d5.gif)

SwiftUI resets the `@State` of the `View1` when it's removed from the view hierarchy. Fortunately there's a simple workaround: you must put all the things that are `@State` and that must survive the transitions in an `@ObservableObject` class (i.e. in a `ViewModel`) this way:

```
import SwiftUI
import NavigationStack

struct ContentView : View {
    var body: some View {
        NavigationStackView {
            View1()
        }
    }
}

class View1ViewModel: ObservableObject {
    @Published var text = ""
}

struct View1: View {
    @ObservedObject var view1ViewModel = View1ViewModel()

    var body: some View {
        ZStack {
            Color.yellow.edgesIgnoringSafeArea(.all)
            VStack {
                PushView(destination: View2()) {
                    Text("PUSH")
                }
                TextField("Type something...", text: $view1ViewModel.text)
            }
        }
    }
}

struct View2: View {
    var body: some View {
        ZStack {
            Color.green.edgesIgnoringSafeArea(.all)
            
            PopView {
                Text("POP")
            }
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```

This time the result is:

![Feb-08-2020 15-20-09](https://user-images.githubusercontent.com/5569047/74086787-94c17180-4a86-11ea-8f05-364c071fa43d.gif)

Let me know if I answered your question and feel free to post some minimum viable examples in order for me to directly check them and help you debugging.

**Comment by bluelobe** [comment]
Hi.
Thanks for answering. I discovered the cause to be the native Picker’s response method interfering with the TextView UIRepresentable. I had to give up using the Picker and just used 2 Buttons.
Vip Malixi
"Commit random acts of kindness."– The Dalai Lama
 

    On Saturday, February 8, 2020, 10:24:45 PM GMT+8, Matteo <notifications@github.com> wrote:  
 
 
Hi @bluelobe I guess I got your problem, but I'll show you an example, so that you can tell me if it's actually the problem you are experiencing. The problem is due to SwiftUI resetting all the @State properties when a view is removed from the hierarchy. It's not a SwiftUI bug, it's just a SwiftUI behaviour. Take a look at this example (you can copy paste it and try yourself):
import SwiftUI
import NavigationStack

struct ContentView : View {
    var body: some View {
        NavigationStackView {
            View1()
        }
    }
}

struct View1: View {
    @State private var text = ""

    var body: some View {
        ZStack {
            Color.yellow.edgesIgnoringSafeArea(.all)
            VStack {
                PushView(destination: View2()) {
                    Text("PUSH")
                }
                TextField("Type something...", text: $text)
            }
        }
    }
}

struct View2: View {
    var body: some View {
        ZStack {
            Color.green.edgesIgnoringSafeArea(.all)
            
            PopView {
                Text("POP")
            }
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

The result is:



SwiftUI resets the @State of the View1 when it's removed from the view hierarchy. Fortunately there's a simple workaround: you must put all the things that are @State and that must survive the transitions in an @ObservableObject class (i.e. in a ViewModel) this way:
import SwiftUI
import NavigationStack

struct ContentView : View {
    var body: some View {
        NavigationStackView {
            View1()
        }
    }
}

class View1ViewModel: ObservableObject {
    @Published var text = ""
}

struct View1: View {
    @ObservedObject var view1ViewModel = View1ViewModel()

    var body: some View {
        ZStack {
            Color.yellow.edgesIgnoringSafeArea(.all)
            VStack {
                PushView(destination: View2()) {
                    Text("PUSH")
                }
                TextField("Type something...", text: $view1ViewModel.text)
            }
        }
    }
}

struct View2: View {
    var body: some View {
        ZStack {
            Color.green.edgesIgnoringSafeArea(.all)
            
            PopView {
                Text("POP")
            }
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

This time the result is:



Let me know if I answered your question and feel free to post some minimum viable examples in order for me to directly check them and help you debugging.
