### ISSUE TITLE
PushView with Buttons

### ISSUE THREAD

**Issue by vmshaneeb** [biobeats/swiftui-navigation-stack#30]
How do I PushView with buttons...??

This does nothing..
                        `PushView(destination: SignInView()) {
                            Button(action: {
                                self.isActive.toggle()
                            }) {
                                HStack {
                                    Image("mail-icon")
                                    Text("  Login with Email/Mobile")
                                        .font(.custom("Avenir Next Bold", size: 14.0))
                                    Spacer()
                                }
                            }
                            .modifier(PrimaryButton(colorInput: .red))
                        }`

But this works fine..??

`PushView(destination: SignInView()) {
HStack {
                                    Image("mail-icon")
                                    Text("  Login with Email/Mobile")
                                        .font(.custom("Avenir Next Bold", size: 14.0))
                                    Spacer()
                                }
 .modifier(PrimaryButton(colorInput: .red))
                        }`

**Comment by matteopuc** [comment]
Hi @vmshaneeb! With the `NavigationStack` you can also `push` programmatically (since you were talking about `Button` I think this is what you want):

```
struct MyView: View {
    @EnvironmentObject private var navigationStack: NavigationStack

    var body: some View {
        Button(action: {
            //do whatever you want
            self.navigationStack.push(SignInView())
        }, label: {
            Text("PUSH")
        })
    }
}
```

**Comment by vmshaneeb** [comment]
@matteopuc Cool... (Y)

Thanks bro...
